# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import eventex.subscriptions.validater


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20160308_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cpf',
            field=models.CharField(max_length=11, validators=[eventex.subscriptions.validater.validate_cpf], verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
