# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160331_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Kind',
            new_name='kind',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
